### ISSUE TITLE
Can not find plugin in Kong Manager

### ISSUE THREAD

**Issue by vietduc030496** [jeromeguillaume/kong-plugin-soap-xml-handling#6]
1. I followed the docker installation instructions step by step except step 3: install license
2. Access Kong Manager by link : http://localhost:8002/
3. Access plugin and search "SOAP" but can not find any plugin (see image below)
 
![image](https://github.com/jeromeguillaume/kong-plugin-soap-xml-handling/assets/40557559/f4fb6feb-6b50-4435-96e4-6ae029326da0)

4. I checked docker and there are plugin source folders

![image](https://github.com/jeromeguillaume/kong-plugin-soap-xml-handling/assets/40557559/c04a4a66-c98c-4c47-92b4-97cde48caaea)

What should I do fix it? 
Do I need a license because I am using Kong Manager is running in Free Mode
Thank you.

**Comment by osaka911** [comment]
Did you fixed that?

**Comment by vietduc030496** [comment]
you can install plugin with API because Kong Manage free not support display custom plugin
link reference API install plugin: https://docs.konghq.com/gateway/latest/get-started/rate-limiting/
